### ISSUE TITLE
Add button to options page to prime_the_pump()

### ISSUE THREAD

**Issue by jaredatch** [jaredatch/EA-Share-Count#15]
See https://github.com/thomasgriffin/tgm-batch-updates/blob/master/tgm-batch-updates.php

So I'm thinking we add maybe add a button to the settings that which clicked primes the pump via the neat batch update method Thomas did above. Only thing is we might want to provide some sort of setting (or filter) for post types in case it needs to also prime for pages or custom post types.

The other thing is would there every be a use case for a button like "Refresh All Counts"? Essentially running a batch update that pulls new counts regardless of if the key exists or not?

**Comment by billerickson** [comment]
I think this is a fairly edge-case usage and doesn't belong in core. The amount of people who are:
a) Querying based on share count data; and
b) Are not comfortable running `ea_share()->core->prime_the_pump();` via code in their theme/plugin

is pretty slim. This would be better implemented as an addon plugin, rather than adding an additional setting that 99.99% of installs won't use.

I'm closing for now.
