### ISSUE TITLE
Feature to "preserve" non-SSL counts

### ISSUE THREAD

**Issue by jaredatch** [jaredatch/EA-Share-Count#38]
Despite being 2016 most (all?) the social services still tie the share-count to a protocol specific URL (which is completely ridiculous).

Of course because of this, your share counts all reset to zero when you go SSL, which is a big ordeal (social proof, blah, blah, blah).

Client sent me this today https://www.freewheelings.com/converting-wordpress-https-ssl-preserving-social-share-button-counts/

Basically what this other plugin does, is if you have it configured, it checks both versions of the URLs and combines the counts. I think this is something we should add and would be a very unique feature as no one else does this (that I have seen) other than this plugin.

Ideally a checkbox with "Preserve non-SSL share counts" or similar. When enabled, on post checking we would run 2 API call instead of 1 - check http _and_ https - then combine the counts before storing in post meta.

I'd say we go even one step further and add a filter that you can define the SSL implementation date. That way posts before that date which would have http versions we run the dual checks on, while posts after that date we just have the single https API check since it never existed previously. 

I think I have a client who eventually will want this (in the next few months), but wanted to get your thoughts.

**Comment by billerickson** [comment]
@jaredatch is this something you'd like to add for 1.7.0? I'd still prefer to build this as an add-on plugin as I think it will needlessly complicate the UI for the majority of users. But I do see it as a killer feature for certain users.

We should add whatever filters are necessary in EASC core to implement a purely code-based approach (ex: for all posts with `date( 'U' ) < strotime( 'January 1, 2016' )` get the http version as well).

I'd also love to see some sort of editor in the metabox so you could manage it on a per-post basis. About to change the URL of a post? Enter the old URL here so those share counts aren't lost.

**Comment by saxisme** [comment]
Hello @jaredatch @billerickson.
(I have been looking around on the repo and didn't find any mention about it)

This idea could be useful also in the case the permalink structure changes.
I have a client that is changing it and was wondering what your suggestions might be, so that the counts gets summed between the two version of the URL (the idea of the date it's really good!)

Some thoughts on it also here:
http://lutfitorla.com/1121/keeping-sharethis-digg-digg-social-counts-after-a-wordpress-permalink-change/
and
https://moz.com/community/q/change-url-structure-and-keeping-the-social-media-likes-shares

Thanks

**Comment by jaredatch** [comment]
Moved to new Shared Counts repo.

https://github.com/jaredatch/Shared-Counts/issues/1
