### ISSUE TITLE
Twitter, Pinterest share counts are 0 on all pages.

### ISSUE THREAD

**Issue by Goldenis** [jaredatch/EA-Share-Count#64]
Hi @jaredatch 
http://blog.paleohacks.com/coconut-flour-pancakes/
the twitter, pinterest share counts are 0 on all pages.
on previous versions, it works well though.
Can you check why?

Thanks.

**Comment by jaredatch** [comment]
Twitter count was killed off some months ago by Twitter. That hasn't functioned since then. For this, we added the setting where 0 counts can be omitted, that way it doesn't show a fat zero.

We have a previous ticket that contains some possible unofficial 3rd party work arounds, but none of those have been implemented yet, see https://github.com/jaredatch/EA-Share-Count/issues/39

Pinterest should definitely be working though. @billerickson has it working on one of his large clients. Can you confirm the Pinterest API is checked on the plugin settings page?

**Comment by Goldenis** [comment]
@jaredatch Pinterest API was checked already.

**Comment by Goldenis** [comment]
@jaredatch Can you check why PInterest still shows 0?

**Comment by jaredatch** [comment]
Pinterest counts should start to show up as the cache expires.

**Comment by Goldenis** [comment]
I've disabled all caches from the site but still shows 0. are you using §`like_count` from PInterest responds?

**Comment by billerickson** [comment]
No, we're using `count` from Pinterest. This [this result](http://api.pinterest.com/v1/urls/count.json?callback=receiveCount&url=http://blog.paleohacks.com/turkey-bacon-burger-recipe/):

```
{"url":"http://blog.paleohacks.com/turkey-bacon-burger-recipe/","count":173}
```

**Comment by jaredatch** [comment]
Sorry, I should have clarified. The server cache isn't the only cache - EASC has it's own cache, otherwise the plugin would end up crashing the server from the requests.

Cache times depend on how old the post is (and are adjustable via a filter).

They should expire roughly over 24 hours or so.

See http://blog.paleohacks.com/edible-cookie-dough/

Also you can manually refresh the cache using the metabox on the post edit screen (https://cl.ly/1f3W1W1v2N13).

**Comment by Goldenis** [comment]
@jaredatch Thanks for quick response.

I've already tried to refresth the cache using the metabox but it didn't work.

http://blog.paleohacks.com/coconut-flour-pancakes/

check the above link, please.

from the [api](http://api.pinterest.com/v1/urls/count.json?callback=receiveCount&url=http://blog.paleohacks.com/coconut-flour-pancakes/), it's returnig over 100K counts but in meta box, it still shows 0.

**Comment by jaredatch** [comment]
Maybe there is a slight delay in the refresh. Shows for me https://cl.ly/1W3m3g1n3c1J

**Comment by jaredatch** [comment]
Also, in a previous update, we changed how the refresh works to try to speed things up.

When a refresh is triggered, it returns the old (expired) counts, and then runs the refresh right before the server request ends.

So when you trigger a refresh in the metabox, even though the refresh is happening, I think it might be showing the stale numbers. I'll how to look into that deeper and see if thats the case or not.
