### ISSUE TITLE
Not counting

### ISSUE THREAD

**Issue by mofizul21** [jaredatch/EA-Share-Count#97]
Thanks for making the plugin.

I've installed and configured the plugin here for the testing purpose- https://mofiz.celigre.com/uncategorized/doloremque-asperiores-eos-est-laborum-consequatur I've share two times in Facebook and one time in Twitter, it's shared, but not showing the count number- http://prntscr.com/i3u2x5 it's showing 0 (zero).

How to I can fix the plugin?

Regards-
Mofi

**Comment by jaredatch** [comment]
hey @mofizul21,

Version 2.0 of EASC is in beta. Because of some breaking changes and substantial improvements, v2 is being released and rebranded as "Shared Counts" plugin.

Anyways, the beta version should be stable and includes fixes and improvements that might help with the issue you're encountering.

When you get a chance, I recommend downloading and installed the new Shared Counts plugin (deactivate EASC).

https://github.com/jaredatch/Shared-Counts/archive/develop.zip

If you still have issues after switching to Shared Counts you can open a [new issue](https://github.com/jaredatch/Shared-Counts/issues).
